export const FETCH_RULE_IZIN = 'FETCH_RULE_IZIN';
export const SET_FORM_IZIN = 'SET_FORM_IZIN';
export const FETCH_IZIN_DATA = 'FETCH_IZIN_DATA';
export const SET_ACTIVITY_CODE_IZIN = 'SET_ACTIVITY_CODE_IZIN';
