export const FETCH_TIME_PRESENSI = 'FETCH_TIME_PRESENSI';
export const FETCH_PRESENSI_MASUK = 'FETCH_PRESENSI_MASUK';
export const FETCH_PRESENSI_PULANG = 'FETCH_PRESENSI_PULANG';
export const FETCH_ACTIVITY_CODE_PRESENSI = 'FETCH_ACTIVITY_CODE_PRESENSI';
export const FETCH_LOKASI_PRESENSI = 'FETCH_LOKASI_PRESENSI';
export const FETCH_TIPE_PEGAWAI_PRESENSI = 'FETCH_TIPE_PEGAWAI_PRESENSI';
export const FETCH_WAKTU_PRESENSI_USER = 'FETCH_WAKTU_PRESENSI_USER';
export const FETCH_TIPE_PEGAWAI_PRESENSI_SHIFT =
  'FETCH_TIPE_PEGAWAI_PRESENSI_SHIFT';
export const FETCH_WAKTU_PRESENSI_SHIFT = 'FETCH_WAKTU_PRESENSI_SHIFT';
export const FETCH_ID_WAKTU_SHIFT = 'FETCH_ID_WAKTU_SHIFT';
export const FETCH_DATE_PRESENSI_AFTER_GOHOME =
  'FETCH_DATE_PRESENSI_AFTER_GOHOME';
export const SET_ENABLE_PRESENSI = 'SET_ENABLE_PRESENSI';
export const SET_TIME_PRESENSI_SHIFT = 'SET_TIME_PRESENSI_SHIFT';
