export const FETCH_HISTORY_PRESENSI_MINGGU = 'FETCH_HISTORY_PRESENSI_MINGGU';
export const FETCH_HISTORY_PRESENSI_BULAN = 'FETCH_HISTORY_PRESENSI_BULAN';
export const FETCH_HISTORY_PRESENSI_FILTER = 'FETCH_HISTORY_PRESENSI_FILTER';
export const FETCH_KALKULASI_PRESENSI_MINGGU =
  'FETCH_KALKULASI_PRESENSI_MINGGU';
export const FETCH_KALKULASI_PRESENSI_BULAN = 'FETCH_KALKULASI_PRESENSI_BULAN';
export const FETCH_KALKULASI_PRESENSI_FILTER =
  'FETCH_KALKULASI_PRESENSI_FILTER';
